In [ ]:
import numpy as np
import tensorflow
import keras

In [ ]:
r = np.array([[0,0,0,0,0,0,0],[0,-1,1,1,1,-1,0],[0,1,-1,1,1,-1,0],[0,0,-1,1,1,0,0],[0,-1,1,1,1,0,0],[0,1,1,-1,1,-1,0],[0,0,0,0,0,0,0]])
g = np.array([[0,0,0,0,0,0,0],[0,1,-1,-1,1,-1,0],[0,1,-1,0,1,-1,0],[0,1,0,0,-1,0,0],[0,-1,1,1,1,1,0],[0,-1,1,0,-1,-1,0],[0,0,0,0,0,0,0]])
b = np.array([[0,0,0,0,0,0,0],[0,1,-1,-1,0,-1,0],[0,1,-1,0,1,0,0],[0,1,0,0,-1,0,0],[0,0,1,0,0,1,0],[0,-1,-1,1,-1,0,0],[0,0,0,0,0,0,0]])

In [11]:
r_filter = np.array([[0,0,0],[0,-1,1],[0,1,-1]])
g_filter = np.array([[1,0,0],[0,0,-1],[0,1,1]])
b_filter = np.array([[1,1,1],[1,1,1],[0,1,-1]])

In [ ]:
r_filter = np.array([[1,0,0],[0,1,1],[1,-1,-1]])
g_filter = np.array([[1,1,0],[1,1,-1],[1,-1,-1]])
b_filter = np.array([[0,0,0],[0,0,0],[0,1,0]])

In [12]:
def convolution(input, filter, stride):
    map_filter = np.zeros(shape=(3,3),dtype=np.int8)
    
    for color in range(len(input)):
        step_i = 0
        for i in range(len(filter)):
            step_j = 0
            for j in range(len(filter)):
                aux = np.array(input[color][i+step_i:i+step_i+3,j+step_j:j+step_j+3])
                map_filter[i][j] += np.sum(aux*filter[color])
                step_j+=1
            step_i+=1
            
    return map_filter
                
           


In [13]:
input = np.array([r,g,b])
filter = np.array([r_filter,g_filter,b_filter])
print(convolution(input,filter,2))

[[ 7 -3 -2]
 [-3  1  3]
 [-2  4  2]]


In [ ]:
result_r = np.dot(r_slice,r_filter)
print(result_r)

In [ ]:
result_b = np.dot(b_slice,b_filter)
print(result_b)

In [ ]:
result_g = np.dot(g_slice,g_filter)
print(result_g)

In [ ]:
layer = [r_slice,g_slice,b_slice]
filter = [r_filter,g_filter,b_filter]
print(layer)

In [31]:
result = np.dot(result_r,result_g)
print(result)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3
3
3


In [57]:
x= r_filter*g_filter
x

array([[ 0,  0,  0],
       [ 0,  0, -1],
       [ 0,  1, -1]])

In [108]:
r[2:3,2:3]

array([[-1]])

In [65]:
print(r[3][0:3])

[ 0  0 -1]
