# Jupyter Notebook para programação de uma convolucão matricial 
### Exemplo do livro Fundamentals of Deep Learning do Buduma - página 96

#### Importação de bibliotecas

In [3]:
import numpy as np

#### Criando variáveis de entrada 
- Dimensão: 5 x 5 x 3
- Zero padding p = 1

In [4]:
input_r = np.array([[0,0,0,0,0,0,0],[0,-1,1,1,1,-1,0],[0,1,-1,1,1,-1,0],[0,0,-1,1,1,0,0],[0,-1,1,1,1,0,0],[0,1,1,-1,1,-1,0],[0,0,0,0,0,0,0]])
input_g = np.array([[0,0,0,0,0,0,0],[0,1,-1,-1,1,-1,0],[0,1,-1,0,1,-1,0],[0,1,0,0,-1,0,0],[0,-1,1,1,1,1,0],[0,-1,1,0,-1,-1,0],[0,0,0,0,0,0,0]])
input_b = np.array([[0,0,0,0,0,0,0],[0,1,-1,-1,0,-1,0],[0,1,-1,0,1,0,0],[0,1,0,0,-1,0,0],[0,0,1,0,0,1,0],[0,-1,-1,1,-1,0,0],[0,0,0,0,0,0,0]])

inputs = np.array([input_r,input_g,input_b])

#### Criando filtros
- Dimensão: 3 x 3 x 3

In [5]:
r_filter1 = np.array([[0,0,0],[0,-1,1],[0,1,-1]])
g_filter1 = np.array([[1,0,0],[0,0,-1],[0,1,1]])
b_filter1 = np.array([[1,1,1],[1,1,1],[0,1,-1]])

filter1 = np.array([r_filter1,g_filter1,b_filter1])

In [6]:
r_filter2 = np.array([[1,0,0],[0,1,1],[1,-1,-1]])
g_filter2 = np.array([[1,1,0],[1,1,-1],[1,-1,-1]])
b_filter2 = np.array([[0,0,0],[0,0,0],[0,1,0]])

filter2 = np.array([r_filter2,g_filter2,b_filter2])

#### Função que realiza a convolução utilizando:
- Uma entrada
- Um filtro
- Um valor de stride

In [7]:
def convolution(input, filter, stride):
    feature_map = np.zeros(shape=(3,3),dtype=np.int8)
    
    for color in range(len(input)):
        step_i = 0
        for i in range(len(filter)):
            step_j = 0
            for j in range(len(filter)):
                aux = np.array(input[color][i+step_i:i+step_i+3,j+step_j:j+step_j+3])
                feature_map[i][j] += np.sum(aux*filter[color])
                step_j+=1
            step_i+=1
            
    return feature_map

#### Mostrando o resultado da convolução com os parâmetros desejados

In [12]:
print(convolution(inputs,filter1,2))

[[ 7 -3 -2]
 [-3  1  3]
 [-2  4  2]]
